language: python

pylint:
    disable: 
        - test
        - hsdf
pep8:
    disable:
        - test2
        - lsdjkf

conventions:
    variable:
        naming: underscore
        max_length: 20
    function:
        naming: camelCase

complexity:
    cc_threshold: 14

