language: python
python:
  - "2.6" # deprecated
  - "2.7"
  - "pypy"
#  - "3.2"
#  - "3.3" # not sure
#  - "3.4"
#  - "pypy3"
#  - "nightly"

notifications:
  email:
    recipients:
      - me@cwoebker.com
    #on_success: [always|never|change] # default: change
    #on_failure: change # [always|never|change] # default: always

# environment variables to set
#env: RELO_PATH=/path/to/relo

before_install:
  - pip install -r reqs.txt
install:
  - python setup.py install

#before_script:
#  - pip install nose2

#script:
#  - nose2 --verbose test_pen
before_script:
  - pip install nose

script:
  - nosetests
