language: python
python:
  - "2.7"
  - "pypy"

notifications:
  email:
    recipients:
      - me@cwoebker.com
    on_success: change
    on_failure: always

before_install:
  - pip install pipenv
  - pipenv install
install:
  - python setup.py install

#before_script:
#  - pip install nose2

#script:
#  - nose2 --verbose test_pen
before_script:
  - pip install nose

script:
  - nosetests
