language: python
python:
  - "2.6"
  - "2.7"
#  - "3.2"
# environment variables to set
#env: RELO_PATH=/path/to/relo

# command to run tests
#before_script:
#  -
script: nosetests
#after_script:
#  -

# command to install dependencies
#before_command:
#  -
install:
  - pip install -r reqs.txt --use-mirrors
#after_command:
#  -